# -*- mode: ruby -*-
# Vagrant file for Vagrant 1.2.x, generated with macman.
# **YOU SHOULD NOT EDIT THIS FILE MANUALLY.**
# You had better edit templates and presets, then run the generator again.
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "%(name)s"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  #config.vm.box_url = "%(url)s"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "%(ip)s"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "local/path", "remote/path"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
     # Boot mode: either :gui or :headless.
     vb.gui = %(gui)s

     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "%(ram)s"]
     vb.customize ["modifyvm", :id, "--cpus", "%(cpus)s"]
     vb.customize ["modifyvm", :id, "--vram", "%(vram)s"]
  end

  # SSH forwarding.
  config.ssh.forward_agent = :%(ssh_forward_agent)s

end
